name 'cookbook_c'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures cookbook_c'
long_description 'Installs/Configures cookbook_c'
version '0.1.0'
