name 'cookbook_a'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures cookbook_a'
long_description 'Installs/Configures cookbook_a'
version '0.1.0'
